ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF6';

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CMP_ORDER_ITEM CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CMP_ORDER CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CMP_DATA_CASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CMP_STRUCT_CASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CMP_NO_PK_LOG CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CMP_USER CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CMP_ORACLE_ONLY CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE CMP_USER (
  USER_ID NUMBER(10,0) NOT NULL,
  USER_CODE VARCHAR2(20 CHAR) NOT NULL,
  USER_NAME VARCHAR2(50 CHAR) NOT NULL,
  EMAIL VARCHAR2(100 CHAR) NULL,
  USER_STATUS CHAR(1 CHAR) DEFAULT 'A' NOT NULL,
  CREDIT_SCORE NUMBER(10,2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  REMARK VARCHAR2(200 CHAR) NULL,
  CONSTRAINT PK_CMP_USER PRIMARY KEY (USER_ID),
  CONSTRAINT UQ_CMP_USER_CODE UNIQUE (USER_CODE)
);

CREATE INDEX IDX_CMP_USER_STATUS ON CMP_USER(USER_STATUS);

CREATE TABLE CMP_ORDER (
  ORDER_ID NUMBER(19,0) NOT NULL,
  USER_ID NUMBER(10,0) NOT NULL,
  ORDER_NO VARCHAR2(30 CHAR) NOT NULL,
  AMOUNT NUMBER(12,2) NOT NULL,
  CURRENCY_CODE CHAR(3 CHAR) DEFAULT 'CNY' NOT NULL,
  PAID_FLAG NUMBER(1,0) DEFAULT 0 NOT NULL,
  ORDER_TIME TIMESTAMP NOT NULL,
  PAID_TIME TIMESTAMP NULL,
  NOTE VARCHAR2(200 CHAR) NULL,
  CONSTRAINT PK_CMP_ORDER PRIMARY KEY (ORDER_ID),
  CONSTRAINT UQ_CMP_ORDER_NO UNIQUE (ORDER_NO),
  CONSTRAINT FK_CMP_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES CMP_USER(USER_ID)
);

CREATE INDEX IDX_CMP_ORDER_USER_TIME ON CMP_ORDER(USER_ID, ORDER_TIME);

CREATE TABLE CMP_ORDER_ITEM (
  ORDER_ID NUMBER(19,0) NOT NULL,
  LINE_NO NUMBER(10,0) NOT NULL,
  SKU_CODE VARCHAR2(30 CHAR) NOT NULL,
  QTY NUMBER(10,0) NOT NULL,
  UNIT_PRICE NUMBER(10,2) NOT NULL,
  DISCOUNT_RATE NUMBER(5,4) DEFAULT 0 NOT NULL,
  EXT_TEXT VARCHAR2(200 CHAR) NULL,
  CONSTRAINT PK_CMP_ORDER_ITEM PRIMARY KEY (ORDER_ID, LINE_NO),
  CONSTRAINT FK_CMP_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES CMP_ORDER(ORDER_ID)
);

CREATE TABLE CMP_DATA_CASE (
  ID NUMBER(10,0) NOT NULL,
  TEXT_VALUE VARCHAR2(50 CHAR) NULL,
  NUM_VALUE NUMBER(18,6) NULL,
  DT_VALUE TIMESTAMP NULL,
  NULLABLE_FLAG VARCHAR2(10 CHAR) NULL,
  WHITESPACE_VALUE VARCHAR2(50 CHAR) NULL,
  CASE_VALUE VARCHAR2(50 CHAR) NULL,
  CONSTRAINT PK_CMP_DATA_CASE PRIMARY KEY (ID)
);

CREATE TABLE CMP_STRUCT_CASE (
  ID NUMBER(10,0) NOT NULL,
  CODE VARCHAR2(30 CHAR) NOT NULL,
  DESCRIPTION VARCHAR2(120 CHAR) NULL,
  FLAG NUMBER(10,0) DEFAULT 0 NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_CMP_STRUCT_CASE PRIMARY KEY (ID),
  CONSTRAINT UQ_CMP_STRUCT_CODE UNIQUE (CODE)
);

CREATE TABLE CMP_NO_PK_LOG (
  EVENT_ID NUMBER(10,0) NOT NULL,
  EVENT_TYPE VARCHAR2(30 CHAR) NOT NULL,
  PAYLOAD VARCHAR2(100 CHAR) NULL,
  CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE CMP_ORACLE_ONLY (
  ID NUMBER(10,0) NOT NULL,
  ORACLE_FEATURE VARCHAR2(40 CHAR) NOT NULL,
  CONSTRAINT PK_CMP_ORACLE_ONLY PRIMARY KEY (ID)
);

COMMENT ON TABLE CMP_USER IS 'core users for compare tests';
COMMENT ON TABLE CMP_STRUCT_CASE IS 'this table is intentionally different by database';
COMMENT ON COLUMN CMP_STRUCT_CASE.CODE IS 'oracle code length is 30';

INSERT INTO CMP_USER (USER_ID, USER_CODE, USER_NAME, EMAIL, USER_STATUS, CREDIT_SCORE, CREATED_AT, REMARK) VALUES
(1, 'U1001', 'Alice', 'alice@example.com', 'A', 98.50, TO_TIMESTAMP('2024-01-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'core customer');
INSERT INTO CMP_USER (USER_ID, USER_CODE, USER_NAME, EMAIL, USER_STATUS, CREDIT_SCORE, CREATED_AT, REMARK) VALUES
(2, 'U1002', 'Bob', 'bob@example.com', 'A', 77.00, TO_TIMESTAMP('2024-02-01 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'has trailing spaces  ');
INSERT INTO CMP_USER (USER_ID, USER_CODE, USER_NAME, EMAIL, USER_STATUS, CREDIT_SCORE, CREATED_AT, REMARK) VALUES
(3, 'U1003', 'Cathy', 'cathy@example.com', 'I', 66.66, TO_TIMESTAMP('2024-03-20 12:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'CaseTest');
INSERT INTO CMP_USER (USER_ID, USER_CODE, USER_NAME, EMAIL, USER_STATUS, CREDIT_SCORE, CREATED_AT, REMARK) VALUES
(4, 'U1004', 'David', NULL, 'A', 0.00, TO_TIMESTAMP('2024-04-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL);

INSERT INTO CMP_ORDER (ORDER_ID, USER_ID, ORDER_NO, AMOUNT, CURRENCY_CODE, PAID_FLAG, ORDER_TIME, PAID_TIME, NOTE) VALUES
(9001, 1, 'SO-202401-001', 120.50, 'CNY', 1, TO_TIMESTAMP('2024-01-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-01-15 10:05:00', 'YYYY-MM-DD HH24:MI:SS'), 'paid');
INSERT INTO CMP_ORDER (ORDER_ID, USER_ID, ORDER_NO, AMOUNT, CURRENCY_CODE, PAID_FLAG, ORDER_TIME, PAID_TIME, NOTE) VALUES
(9002, 1, 'SO-202401-002', 88.00, 'CNY', 0, TO_TIMESTAMP('2024-01-16 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'waiting payment');
INSERT INTO CMP_ORDER (ORDER_ID, USER_ID, ORDER_NO, AMOUNT, CURRENCY_CODE, PAID_FLAG, ORDER_TIME, PAID_TIME, NOTE) VALUES
(9003, 2, 'SO-202402-003', 35.90, 'USD', 1, TO_TIMESTAMP('2024-02-11 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-02-11 09:45:00', 'YYYY-MM-DD HH24:MI:SS'), NULL);

INSERT INTO CMP_ORDER_ITEM (ORDER_ID, LINE_NO, SKU_CODE, QTY, UNIT_PRICE, DISCOUNT_RATE, EXT_TEXT) VALUES
(9001, 1, 'SKU-A-001', 2, 30.00, 0.1000, '{"channel":"app"}');
INSERT INTO CMP_ORDER_ITEM (ORDER_ID, LINE_NO, SKU_CODE, QTY, UNIT_PRICE, DISCOUNT_RATE, EXT_TEXT) VALUES
(9001, 2, 'SKU-B-009', 1, 60.50, 0.0000, '{"channel":"app"}');
INSERT INTO CMP_ORDER_ITEM (ORDER_ID, LINE_NO, SKU_CODE, QTY, UNIT_PRICE, DISCOUNT_RATE, EXT_TEXT) VALUES
(9002, 1, 'SKU-C-100', 4, 22.00, 0.0000, '{"channel":"web"}');
INSERT INTO CMP_ORDER_ITEM (ORDER_ID, LINE_NO, SKU_CODE, QTY, UNIT_PRICE, DISCOUNT_RATE, EXT_TEXT) VALUES
(9003, 1, 'SKU-D-201', 1, 35.90, 0.0500, '{"channel":"store"}');

INSERT INTO CMP_DATA_CASE (ID, TEXT_VALUE, NUM_VALUE, DT_VALUE, NULLABLE_FLAG, WHITESPACE_VALUE, CASE_VALUE) VALUES
(1, 'same-row', 100.123456, TO_TIMESTAMP('2024-01-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'keep-space', 'CaseSensitive');
INSERT INTO CMP_DATA_CASE (ID, TEXT_VALUE, NUM_VALUE, DT_VALUE, NULLABLE_FLAG, WHITESPACE_VALUE, CASE_VALUE) VALUES
(2, 'trim-check', 9.900000, TO_TIMESTAMP('2024-01-02 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'abc', 'abc');
INSERT INTO CMP_DATA_CASE (ID, TEXT_VALUE, NUM_VALUE, DT_VALUE, NULLABLE_FLAG, WHITESPACE_VALUE, CASE_VALUE) VALUES
(3, 'case-check', 1.000000, TO_TIMESTAMP('2024-01-03 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Y', 'A', 'mixed');
INSERT INTO CMP_DATA_CASE (ID, TEXT_VALUE, NUM_VALUE, DT_VALUE, NULLABLE_FLAG, WHITESPACE_VALUE, CASE_VALUE) VALUES
(4, NULL, 42.420000, NULL, NULL, NULL, NULL);
INSERT INTO CMP_DATA_CASE (ID, TEXT_VALUE, NUM_VALUE, DT_VALUE, NULLABLE_FLAG, WHITESPACE_VALUE, CASE_VALUE) VALUES
(5, 'float-check', 0.333333, TO_TIMESTAMP('2024-01-05 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Y', 'x', 'x');

INSERT INTO CMP_STRUCT_CASE (ID, CODE, DESCRIPTION, FLAG, UPDATED_AT) VALUES
(1, 'S-1', 'oracle variant', 0, TO_TIMESTAMP('2024-01-01 01:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CMP_STRUCT_CASE (ID, CODE, DESCRIPTION, FLAG, UPDATED_AT) VALUES
(2, 'S-2', NULL, 1, TO_TIMESTAMP('2024-01-02 02:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO CMP_NO_PK_LOG (EVENT_ID, EVENT_TYPE, PAYLOAD, CREATED_AT) VALUES
(1, 'sync_start', 'job-001', TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CMP_NO_PK_LOG (EVENT_ID, EVENT_TYPE, PAYLOAD, CREATED_AT) VALUES
(1, 'sync_end', 'job-001', TO_TIMESTAMP('2024-01-01 00:01:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO CMP_ORACLE_ONLY (ID, ORACLE_FEATURE) VALUES
(1, 'service=FREEPDB1');

COMMIT;
