-- Run as SYSDBA.
-- This script creates the dedicated QA schema for MySQL<->DM integration tests.
-- You can change the password before execution.

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER QA_SCHEMA IDENTIFIED BY "QaCompare_2026"';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER USER QA_SCHEMA IDENTIFIED BY "QaCompare_2026"';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

GRANT CREATE SESSION TO QA_SCHEMA;
GRANT CREATE TABLE TO QA_SCHEMA;
GRANT CREATE VIEW TO QA_SCHEMA;
GRANT CREATE INDEX TO QA_SCHEMA;
GRANT CREATE SEQUENCE TO QA_SCHEMA;
GRANT CREATE TRIGGER TO QA_SCHEMA;

-- Optional for easier troubleshooting in test environments:
-- GRANT SELECT ANY TABLE TO QA_SCHEMA;

