-- Run in DM as SYSDBA (or any user with privileges on QA_SCHEMA objects).
-- This script is idempotent and aligned with dev/multidb/mysql/init/01-schema-data.sql.

-- =========================
-- Drop old objects
-- =========================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QA_SCHEMA.CMP_ORDER_ITEM';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QA_SCHEMA.CMP_ORDER';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QA_SCHEMA.CMP_DATA_CASE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QA_SCHEMA.CMP_STRUCT_CASE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QA_SCHEMA.CMP_NO_PK_LOG';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QA_SCHEMA.CMP_USER';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QA_SCHEMA.CMP_DM_ONLY';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- =========================
-- Baseline tables
-- =========================
CREATE TABLE QA_SCHEMA.CMP_USER (
  USER_ID INT NOT NULL,
  USER_CODE VARCHAR2(20) NOT NULL,
  USER_NAME VARCHAR2(50) NOT NULL,
  EMAIL VARCHAR2(100),
  USER_STATUS CHAR(1) DEFAULT 'A' NOT NULL,
  CREDIT_SCORE DECIMAL(10,2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  REMARK VARCHAR2(200),
  CONSTRAINT PK_CMP_USER PRIMARY KEY (USER_ID),
  CONSTRAINT UQ_CMP_USER_CODE UNIQUE (USER_CODE)
);

COMMENT ON TABLE QA_SCHEMA.CMP_USER IS 'core users for compare tests';
CREATE INDEX QA_SCHEMA.IDX_CMP_USER_STATUS ON QA_SCHEMA.CMP_USER(USER_STATUS);

CREATE TABLE QA_SCHEMA.CMP_ORDER (
  ORDER_ID BIGINT NOT NULL,
  USER_ID INT NOT NULL,
  ORDER_NO VARCHAR2(30) NOT NULL,
  AMOUNT DECIMAL(12,2) NOT NULL,
  CURRENCY_CODE CHAR(3) DEFAULT 'CNY' NOT NULL,
  PAID_FLAG INT DEFAULT 0 NOT NULL,
  ORDER_TIME TIMESTAMP NOT NULL,
  PAID_TIME TIMESTAMP,
  NOTE VARCHAR2(200),
  CONSTRAINT PK_CMP_ORDER PRIMARY KEY (ORDER_ID),
  CONSTRAINT UQ_CMP_ORDER_NO UNIQUE (ORDER_NO),
  CONSTRAINT FK_CMP_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES QA_SCHEMA.CMP_USER(USER_ID)
);

COMMENT ON TABLE QA_SCHEMA.CMP_ORDER IS 'orders for compare tests';
CREATE INDEX QA_SCHEMA.IDX_CMP_ORDER_USER_TIME ON QA_SCHEMA.CMP_ORDER(USER_ID, ORDER_TIME);

CREATE TABLE QA_SCHEMA.CMP_ORDER_ITEM (
  ORDER_ID BIGINT NOT NULL,
  LINE_NO INT NOT NULL,
  SKU_CODE VARCHAR2(30) NOT NULL,
  QTY INT NOT NULL,
  UNIT_PRICE DECIMAL(10,2) NOT NULL,
  DISCOUNT_RATE DECIMAL(5,4) DEFAULT 0 NOT NULL,
  EXT_TEXT VARCHAR2(200),
  CONSTRAINT PK_CMP_ORDER_ITEM PRIMARY KEY (ORDER_ID, LINE_NO),
  CONSTRAINT FK_CMP_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES QA_SCHEMA.CMP_ORDER(ORDER_ID)
);

COMMENT ON TABLE QA_SCHEMA.CMP_ORDER_ITEM IS 'order item with composite key';

-- =========================
-- Controlled diff table
-- =========================
CREATE TABLE QA_SCHEMA.CMP_DATA_CASE (
  ID INT NOT NULL,
  TEXT_VALUE VARCHAR2(50),
  NUM_VALUE DECIMAL(18,6),
  DT_VALUE TIMESTAMP,
  NULLABLE_FLAG VARCHAR2(10),
  WHITESPACE_VALUE VARCHAR2(50),
  CASE_VALUE VARCHAR2(50),
  CONSTRAINT PK_CMP_DATA_CASE PRIMARY KEY (ID)
);

COMMENT ON TABLE QA_SCHEMA.CMP_DATA_CASE IS 'rows for null/value/precision/case/trim checks';

-- =========================
-- Intentionally different structure table
-- =========================
CREATE TABLE QA_SCHEMA.CMP_STRUCT_CASE (
  ID INT NOT NULL,
  CODE VARCHAR2(30) NOT NULL,
  FLAG SMALLINT DEFAULT 1 NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  EXTRA_NOTE VARCHAR2(80),
  CONSTRAINT PK_CMP_STRUCT_CASE PRIMARY KEY (ID)
);

COMMENT ON TABLE QA_SCHEMA.CMP_STRUCT_CASE IS 'intentionally different structure in DM';

-- =========================
-- No primary key behavior table
-- =========================
CREATE TABLE QA_SCHEMA.CMP_NO_PK_LOG (
  EVENT_ID INT NOT NULL,
  EVENT_TYPE VARCHAR2(30) NOT NULL,
  PAYLOAD VARCHAR2(100),
  CREATED_AT TIMESTAMP NOT NULL
);

COMMENT ON TABLE QA_SCHEMA.CMP_NO_PK_LOG IS 'table without primary key for behavior validation';

-- =========================
-- DM-only table
-- =========================
CREATE TABLE QA_SCHEMA.CMP_DM_ONLY (
  ID INT NOT NULL,
  DM_FEATURE VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_CMP_DM_ONLY PRIMARY KEY (ID)
);

COMMENT ON TABLE QA_SCHEMA.CMP_DM_ONLY IS 'table only exists in DM';

-- =========================
-- Data: baseline consistency
-- =========================
INSERT INTO QA_SCHEMA.CMP_USER (USER_ID, USER_CODE, USER_NAME, EMAIL, USER_STATUS, CREDIT_SCORE, CREATED_AT, REMARK) VALUES
(1, 'U1001', 'Alice', 'alice@example.com', 'A', 98.50, TO_TIMESTAMP('2024-01-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'core customer');
INSERT INTO QA_SCHEMA.CMP_USER VALUES
(2, 'U1002', 'Bob', 'bob@example.com', 'A', 77.00, TO_TIMESTAMP('2024-02-01 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'has trailing spaces  ');
INSERT INTO QA_SCHEMA.CMP_USER VALUES
(3, 'U1003', 'Cathy', 'cathy@example.com', 'I', 66.66, TO_TIMESTAMP('2024-03-20 12:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'CaseTest');
INSERT INTO QA_SCHEMA.CMP_USER VALUES
(4, 'U1004', 'David', NULL, 'A', 0.00, TO_TIMESTAMP('2024-04-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL);

INSERT INTO QA_SCHEMA.CMP_ORDER VALUES
(9001, 1, 'SO-202401-001', 120.50, 'CNY', 1, TO_TIMESTAMP('2024-01-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-01-15 10:05:00', 'YYYY-MM-DD HH24:MI:SS'), 'paid');
INSERT INTO QA_SCHEMA.CMP_ORDER VALUES
(9002, 1, 'SO-202401-002', 88.00, 'CNY', 0, TO_TIMESTAMP('2024-01-16 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'waiting payment');
INSERT INTO QA_SCHEMA.CMP_ORDER VALUES
(9003, 2, 'SO-202402-003', 35.90, 'USD', 1, TO_TIMESTAMP('2024-02-11 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-02-11 09:45:00', 'YYYY-MM-DD HH24:MI:SS'), NULL);

INSERT INTO QA_SCHEMA.CMP_ORDER_ITEM VALUES
(9001, 1, 'SKU-A-001', 2, 30.00, 0.1000, '{"channel":"app"}');
INSERT INTO QA_SCHEMA.CMP_ORDER_ITEM VALUES
(9001, 2, 'SKU-B-009', 1, 60.50, 0.0000, '{"channel":"app"}');
INSERT INTO QA_SCHEMA.CMP_ORDER_ITEM VALUES
(9002, 1, 'SKU-C-100', 4, 22.00, 0.0000, '{"channel":"web"}');
INSERT INTO QA_SCHEMA.CMP_ORDER_ITEM VALUES
(9003, 1, 'SKU-D-201', 1, 35.90, 0.0500, '{"channel":"store"}');

-- =========================
-- Data: controlled differences against MySQL source_db
-- id=1: NULL_DIFF (NULL -> 'N')
-- id=2: VALUE_DIFF when trim_whitespace=false
-- id=3: VALUE_DIFF when ignore_case=false
-- id=4: row missing in target
-- id=5: float precision difference
-- id=6: row extra in target
-- =========================
INSERT INTO QA_SCHEMA.CMP_DATA_CASE VALUES
(1, 'same-row', 100.123456, TO_TIMESTAMP('2024-01-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'keep-space', 'CaseSensitive');
INSERT INTO QA_SCHEMA.CMP_DATA_CASE VALUES
(2, 'trim-check', 9.900000, TO_TIMESTAMP('2024-01-02 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'abc', 'abc');
INSERT INTO QA_SCHEMA.CMP_DATA_CASE VALUES
(3, 'case-check', 1.000000, TO_TIMESTAMP('2024-01-03 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Y', 'A', 'mixed');
INSERT INTO QA_SCHEMA.CMP_DATA_CASE VALUES
(5, 'float-check', 0.333334, TO_TIMESTAMP('2024-01-05 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Y', 'x', 'x');
INSERT INTO QA_SCHEMA.CMP_DATA_CASE VALUES
(6, 'target-extra', 6.666666, TO_TIMESTAMP('2024-01-06 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', 'extra', 'extra');

INSERT INTO QA_SCHEMA.CMP_STRUCT_CASE VALUES
(1, 'S-1', 1, TO_TIMESTAMP('2024-01-01 01:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'dm variant');
INSERT INTO QA_SCHEMA.CMP_STRUCT_CASE VALUES
(2, 'S-2', 1, TO_TIMESTAMP('2024-01-02 02:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL);

INSERT INTO QA_SCHEMA.CMP_NO_PK_LOG VALUES
(1, 'sync_start', 'job-001', TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO QA_SCHEMA.CMP_NO_PK_LOG VALUES
(1, 'sync_end', 'job-001', TO_TIMESTAMP('2024-01-01 00:01:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO QA_SCHEMA.CMP_DM_ONLY VALUES
(1, 'engine=dm8');

COMMIT;

