-- Run after 01-schema-data.sql.
-- Quick verification SQL for QA_SCHEMA test dataset.

SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'QA_SCHEMA' AND TABLE_NAME LIKE 'CMP_%' ORDER BY TABLE_NAME;

SELECT COUNT(*) AS C_USER FROM QA_SCHEMA.CMP_USER;
SELECT COUNT(*) AS C_ORDER FROM QA_SCHEMA.CMP_ORDER;
SELECT COUNT(*) AS C_ITEM FROM QA_SCHEMA.CMP_ORDER_ITEM;
SELECT COUNT(*) AS C_DATA_CASE FROM QA_SCHEMA.CMP_DATA_CASE;
SELECT COUNT(*) AS C_STRUCT_CASE FROM QA_SCHEMA.CMP_STRUCT_CASE;
SELECT COUNT(*) AS C_NO_PK_LOG FROM QA_SCHEMA.CMP_NO_PK_LOG;
SELECT COUNT(*) AS C_DM_ONLY FROM QA_SCHEMA.CMP_DM_ONLY;

SELECT ID, NULLABLE_FLAG, WHITESPACE_VALUE, CASE_VALUE, NUM_VALUE
FROM QA_SCHEMA.CMP_DATA_CASE
ORDER BY ID;

-- Temporary ROW_COUNT_DIFF validation snippets:
-- INSERT INTO QA_SCHEMA.CMP_USER (USER_ID, USER_CODE, USER_NAME, USER_STATUS, CREDIT_SCORE, CREATED_AT)
-- VALUES (10001, 'TMP-ROWCNT', 'TMP', 'A', 0, CURRENT_TIMESTAMP);
-- COMMIT;
-- DELETE FROM QA_SCHEMA.CMP_USER WHERE USER_ID = 10001;
-- COMMIT;

